### ISSUE TITLE
Encryption SDK Requires Node11

### ISSUE THREAD

**Issue by sharkedj** [awslabs/aws-encryption-sdk-javascript#135]
Node11 is not LTS and isn't even supported by AWS Lambda.

IMO, the encryption SDK should support NodeJS10 and _maybe_ NodeJS8.

FWIW, these are the two versions which are currently supported by lambda.

**Comment by germanviscuso** [comment]
Where is that dependency?

**Comment by seebees** [comment]
The Encryption SDK attempts to only use Node.js types as devDependancies.  However, the helpers in material-management-node, for example [here](https://github.com/awslabs/aws-encryption-sdk-javascript/blob/master/modules/material-management-node/src/material_helpers.ts#L33) export the `CipherGCM` type from `"@types/node": "^11.11.4",`

This makes it a little complicated to use that it should be.  We plan to support Node.js v8.

**Comment by sharkedj** [comment]
https://github.com/awslabs/aws-encryption-sdk-javascript/blob/master/modules/kms-keyring/package.json#L29 relies on node 11 types.

AFAIK, `KeyRing` (see https://github.com/awslabs/aws-encryption-sdk-javascript/blob/24fbfa0f9ace67a0185f62cf9851371a992f407a/modules/raw-rsa-keyring-node/src/raw_rsa_keyring_node.ts#L55-L56 ) is the only Node 11 specific type which is being used; but I haven't done a thorough audit.
