### ISSUE TITLE
Add CI checks to verify that our copied KMS types have not drifted

### ISSUE THREAD

**Issue by mattsb42-aws** [awslabs/aws-encryption-sdk-javascript#19]
> @mattsb42-aws
>  mattsb42-aws 3 days ago
> 
> That doesn't mean they'll never change. What happens if/when the SDK types change and we don't?
> 
> If having a common dependency is intractable, can we put something in our CI to test and make sure that the types are continuing to match?
> 
> @seebees
> seebees 6 hours ago Author
> 
> If the types change and we don't nothing will happen to the run time. (In TypeScript all type information is removed at compile time).
> 
> The worst that will happen is that people who are doing development on new KMS Keyrings will not have as pleasant an experience until the types are updated.
> 
> However. This problem is not unique to me. Anyone who wants to consume the v3 sdk in this way will have a similar problem and if/as this happens it will be the JS SDK team that will have the burden to fix it.
> 
> Finally, breaking up the SDK in this way is explicitly done to avoid common dependancies. So while I could just include them, both the JS SDK team and myself have gone to great lengths to avoid this. I think it would be better to drive to a world where we don't need to.
> 
> (A CI style solution is in principle possible, but annoying as I changed the types so that they are independent of other things)
> 
> @mattsb42-aws
> mattsb42-aws 2 minutes ago
> 
>     The worst that will happen is that people who are doing development on new KMS Keyrings will not have as pleasant an experience until the types are updated.
> 
> My concern is more that I'm not seeing any way that we would know if the types are updated.
> 
> That said, this is also something that I am fine moving into an enhancement feature.

**Comment by seebees** [comment]
This was resolved by #66.  The types are pulled directly from the packages.
