### ISSUE TITLE
client-node x-ray integration

### ISSUE THREAD

**Issue by rafaelrpinto** [awslabs/aws-encryption-sdk-javascript#191]
Hi,

I've been looking into the source code and issues but could not find a way to trace the KMS requests made by `client-node` using AWS X-Ray.

Could you please confirm if that's possible?

Thank you.

**Comment by seebees** [comment]
I will try and get you a clear answer.  What environment are you running this in?  AWS Lambda?

**Comment by rafaelrpinto** [comment]
@seebees 

Yes, we are running APIG + Labdas with Node 10. Thank you.

**Comment by seebees** [comment]
The KmsKeyringNode uses a `clientProvider` to create the needed KMS Clients.
The default is the `cacheKmsClients` that will cache the clients per region.
To use AWS X-Ray, you need to wrap the KMS Clients.

You can create your own `clientProvider`
to wrap your own version of the AWS SDK with `captureAWS` like this.

```javascript
const AWSXRay = require('aws-xray-sdk')
const { getClient, cacheClients } = require('@aws-crypto/client-node')
const { KMS } = AWSXRay.captureAWS(require('aws-sdk'))

const clientProvider = cacheClients(getClient(KMS))
```

Or you can wrap the KMS Client returned by `getKmsClient` with `captureAWSClient` from `aws-xray-sdk`.

```javascript
const AWSXRay = require('aws-xray-sdk')
const { getKmsClient, cacheClients } = require('@aws-crypto/client-node')

const clientProvider = cacheClients(region => AWSXRay.captureAWSClient(getKmsClient(region)))
```

Now that you have a `clientProvider` that does what you want,
just pass this to the `KmsKeyringNode`

```javascript
const keyring = new KmsKeyringNode({ clientProvider, /* Your generatorKeyId, and keyIds here */})
```

**Comment by rafaelrpinto** [comment]
@seebees 

Thanks a lot for the explanation. That's exactly what we needed.

Cheers!
